import os

try:
    from SCons.Script import Import
    Import("env")
except ImportError:
    class MockEnv:
        def get(self, key, default="."):
            return default
    env = MockEnv()

def generate_languages_header():
    project_dir = env.get("PROJECT_DIR", ".")
    languages_dir = os.path.join(project_dir, "languages")
    output_file = os.path.join(project_dir, "include", "embedded_languages.h")
    
    if not os.path.exists(languages_dir):
        print("Languages directory not found!")
        return

    langs = []
    for filename in sorted(os.listdir(languages_dir)):
        if filename.endswith(".lng"):
            filepath = os.path.join(languages_dir, filename)
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
            
            # Extract LANG_NAME
            lang_name = ""
            for line in content.splitlines():
                line = line.strip()
                if line.startswith("LANG_NAME="):
                    lang_name = line.split("=", 1)[1].strip()
                    break
            if not lang_name:
                lang_name = os.path.splitext(filename)[0].upper()
            
            langs.append((filename, lang_name, content))
            
    header_content = """// WARNING: This file is automatically generated by embed_languages.py.
// Do not edit this file manually.

#ifndef EMBEDDED_LANGUAGES_H
#define EMBEDDED_LANGUAGES_H

struct EmbeddedLanguage {
  const char* filename;
  const char* name;
  const char* content;
};

"""
    header_content += "static const EmbeddedLanguage EMBEDDED_LANGUAGES[] = {\n"
    for filename, lang_name, content in langs:
        header_content += "  {\n"
        header_content += f'    "{filename}",\n'
        header_content += f'    "{lang_name}",\n'
        header_content += '    R"rawliteral(\n'
        header_content += content.replace("\r\n", "\n")
        if not content.endswith("\n"):
            header_content += "\n"
        header_content += ')rawliteral"\n'
        header_content += "  },\n"
    header_content += "};\n\n"
    header_content += f"static const int EMBEDDED_LANGUAGES_COUNT = {len(langs)};\n\n"
    header_content += "#endif // EMBEDDED_LANGUAGES_H\n"
    
    # Ensure include/ exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"Generated {output_file} with {len(langs)} embedded languages.")

generate_languages_header()
