import os
import json
import gzip

try:
    from SCons.Script import Import
    Import("env")
except ImportError:
    class MockEnv:
        def get(self, key, default="."):
            return default
    env = MockEnv()

def generate_languages_header():
    project_dir = env.get("PROJECT_DIR", ".")
    languages_dir = os.path.join(project_dir, "languages")
    output_file = os.path.join(project_dir, "include", "embedded_languages.h")
    
    if not os.path.exists(languages_dir):
        print("Languages directory not found!")
        return

    langs = []
    for filename in sorted(os.listdir(languages_dir)):
        if filename.endswith(".lng"):
            filepath = os.path.join(languages_dir, filename)
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
            
            entries = []
            entries_dict = {}
            lang_name = ""
            for line in content.splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    key = key.strip()
                    val = val.strip()
                    if key == "LANG_NAME":
                        lang_name = val
                    entries.append((key, val))
                    entries_dict[key] = val
            
            if not lang_name:
                lang_name = os.path.splitext(filename)[0].upper()
            
            json_str = json.dumps(entries_dict, ensure_ascii=False)
            gz_data = gzip.compress(json_str.encode("utf-8"))
            
            langs.append((filename, lang_name, entries, gz_data))
            
    header_content = """// WARNING: This file is automatically generated by embed_languages.py.
// Do not edit this file manually.

#ifndef EMBEDDED_LANGUAGES_H
#define EMBEDDED_LANGUAGES_H

#include <Arduino.h>

struct LangEntry {
  const char* key;
  const char* value;
};

struct EmbeddedLanguage {
  const char* filename;
  const char* name;
  const LangEntry* entries;
  int num_entries;
  const uint8_t* json_gz;
  size_t json_gz_len;
};

"""
    # Write entries arrays and gzipped json arrays
    for idx, (filename, lang_name, entries, gz_data) in enumerate(langs):
        header_content += f"static const LangEntry LANG_ENTRIES_{idx}[] PROGMEM = {{\n"
        for key, val in entries:
            key_esc = key.replace("\\", "\\\\").replace('"', '\\"')
            val_esc = val.replace("\\", "\\\\").replace('"', '\\"')
            header_content += f'  {{"{key_esc}", "{val_esc}"}},\n'
        header_content += "};\n\n"
        
        header_content += f"static const uint8_t LANG_JSON_GZ_{idx}[] PROGMEM = {{\n"
        header_content += ", ".join(f"0x{b:02x}" for b in gz_data)
        header_content += "\n};\n\n"

    # Write languages array
    header_content += "static const EmbeddedLanguage EMBEDDED_LANGUAGES[] = {\n"
    for idx, (filename, lang_name, entries, gz_data) in enumerate(langs):
        header_content += "  {\n"
        header_content += f'    "{filename}",\n'
        header_content += f'    "{lang_name}",\n'
        header_content += f'    LANG_ENTRIES_{idx},\n'
        header_content += f'    {len(entries)},\n'
        header_content += f'    LANG_JSON_GZ_{idx},\n'
        header_content += f'    sizeof(LANG_JSON_GZ_{idx})\n'
        header_content += "  },\n"
    header_content += "};\n\n"
    header_content += f"static const int EMBEDDED_LANGUAGES_COUNT = {len(langs)};\n\n"
    header_content += "#endif // EMBEDDED_LANGUAGES_H\n"
    
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"Generated {output_file} with {len(langs)} embedded languages.")

generate_languages_header()
