[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_port = COM6 (Decommentare o modificare se si desidera specificare una porta specifica)
; monitor_port = COM6

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen/archive/refs/heads/master.zip
    https://github.com/PaulStoffregen/OneWire/archive/refs/heads/master.zip
    https://github.com/milesburton/Arduino-Temperature-Control-Library/archive/refs/heads/master.zip
    bitbank2/AnimatedGIF @ ^1.4.7
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
    ayushsharma82/ElegantOTA @ ^3.1.0
    knolleary/PubSubClient @ ^2.8

build_flags =
    -I include
    -include config.h

extra_scripts = 
    pre:scripts/inject_version.py
    pre:scripts/embed_languages.py
    pre:scripts/extract_html.py
    post:scripts/copy_release.py