[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_port = COM6 (Decommentare o modificare se si desidera specificare una porta specifica)
; monitor_port = COM6

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen/archive/refs/heads/master.zip
    https://github.com/PaulStoffregen/OneWire/archive/refs/heads/master.zip
    https://github.com/milesburton/Arduino-Temperature-Control-Library/archive/refs/heads/master.zip
    bitbank2/AnimatedGIF @ ^1.4.7

build_flags =
    -I include
    -include config.h

extra_scripts = pre:embed_languages.py

